version: '3.7'

services:
  go_proxy:
    build: .
  
  caddy:
    image: caddy
    ports:
      - "5000:80"
    depends_on:
      - go_proxy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config: